FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y build-essential cmake ccache libspdlog-dev librtlsdr-dev libhackrf-dev libliquid-dev nlohmann-json3-dev libmosquitto-dev libgtest-dev libgmock-dev
