FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y libspdlog1 librtlsdr0 libhackrf0 libliquid2d nlohmann-json3-dev libmosquitto1 && \
    apt-get autoremove -y && \
    apt-get clean all && \
    rm -rf /var/lib/apt/lists/

COPY config.json /config.json
COPY build/auto_sdr /usr/bin/auto_sdr
CMD /usr/bin/auto_sdr /config.json